name: Build C++ binaries

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build --config Release

    - name: List build folder
      shell: bash
      run: |
        echo "Files in build folder:"
        ls -l build
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          ls -l build/Release
        fi

    - name: Upload binaries (macOS)
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: sort_add-macos
        path: build/sort_add

    - name: Upload binaries (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: sort_add-win
        path: build/Release/*
